# Generated by Django 6.0 on 2026-01-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of teaching experience', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, help_text="Educational qualification (e.g., Bachelor's in Mathematics)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject expertise (e.g., Mathematics, Physics)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text="Status for teacher approval. Only relevant if role='teacher'", max_length=20, null=True),
        ),
    ]
