# Generated by Django 6.0 on 2026-02-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_duration_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_content/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('assignment', 'Assignment'), ('document', 'Document'), ('link', 'Link'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
